version: '3.8'

services:
  bot:
    build: .
    container_name: muenchen-termin-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    environment:
      - DB_FILE=/app/data/bot_data.db
    labels:
      - "com.centurylinklabs.watchtower.enable=false"  # Exclude from Watchtower monitoring
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
